# Generated by Django 4.0.6 on 2022-07-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_advuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
