# Generated by Django 4.0.6 on 2022-07-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_advuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
