# Generated by Django 4.0.6 on 2022-07-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_post_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='avatar',
        ),
    ]
