# Generated by Django 4.0.6 on 2022-08-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_comment_audio_comment_file_comment_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
