# Generated by Django 4.0.6 on 2022-08-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_post_file_delete_postfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pubdate'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
